### PR TITLE
Enable sklearn 1.2

### LINKED ISSUE #711: Should we use `get_feature_names_out` instead of `get_feature_names`?
With a newer version of scikit-learn 1.2.0 we got the following error emanating from `_causal_analysis.py`:-

```
{
  "code": "ExecutionFailed",
  "category": "UserError",
  "message": {
    "NonCompliant": "Process 'python' exited with code 1 and error message 'Execution failed. Process exited with status code 1. Error: Traceback (most recent call last):\n  File \"create_causal.py\", line 121, in <module>\n    main(args)\n  File \"create_causal.py\", line 98, in main\n    rai_i.compute()\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/responsibleai/rai_insights/rai_insights.py\", line 389, in compute\n    manager.compute()\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/responsibleai/managers/causal_manager.py\", line 341, in compute\n    policy = self._create_policy(\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/responsibleai/managers/causal_manager.py\", line 244, in _create_policy\n    tree = causal_analysis._policy_tree_output(\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/econml/solutions/causal_analysis/_causal_analysis.py\", line 1520, in _policy_tree_output\n    (policy_val, always_trt)) = self._tree(True, Xtest, feature_index,\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/econml/solutions/causal_analysis/_causal_analysis.py\", line 1441, in _tree\n    return intrp, result.X_transformer.get_feature_names(self.feature_names_), treatment_names, policy_values\n  File \"/azureml-envs/azureml_6de821483c371657b39f098361948b90/lib/python3.8/site-packages/econml/solutions/causal_analysis/_causal_analysis.py\", line 228, in get_feature_names\n    cats = self.one_hot_encoder.get_feature_names(\nAttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'\n'. Please check the log file 'user_logs/std_log.txt' for more details."
  },
  "details": [
    {
      "name": "exit_codes",
      "value": {
        "Literal": {
          "Compliant": "1"
        }
      }
    }
  ],
  "error": null,
  "node_info": null
}
```

Looks like the method `get_feature_names` is deprecated in newer version of scikit-learn.  Is it possible to change to API `get_feature_names_out`?

### PR DESCRIPTION
**Pull request by kbattocchi**
Fixes #711

### CODE REVIEW

**Comment by fverac** [comment]
Given that we are trying to support multiple sklearn versions with our package, in the future should we consider testing across multiple sklearn versions as well?

Because right now our tests only check if our package works with the latest compatible version of sklearn right?

**Comment by fverac** [comment]
Should we make a minor update to the cate_treatment_names docstrings which currently say 
```Available only when the featurizer is not None and has a method: `get_feature_names(feature_names)```

Update to something like
```Available only when the featurizer is not None and has one of the following methods: `get_feature_names(feature_names) or get_feature_names_out(feature_names)```

**Comment by fverac** [comment]
> Should we make a minor update to the cate_treatment_names docstrings which currently say `` Available only when the featurizer is not None and has a method: `get_feature_names(feature_names) ``
> 
> Update to something like `` Available only when the featurizer is not None and has one of the following methods: `get_feature_names(feature_names) or get_feature_names_out(feature_names) ``

Also similar thing in _set_transformed_treatment_names in TreatmentExpansionMixin

**Review by fverac — APPROVED** [review]

**Comment by kbattocchi** [comment]
Yes, systematically testing against a wider range of dependencies has long been something we've wanted to support, but our test matrix is already quite large.  This is perhaps something that would be better addressed by nightly tests, which we could add when moving over to GitHub Actions.

But also note that Python 3.7 support was dropped by scikit-learn a while ago, so we're still testing against scikit-learn 1.0.3 when we run our Python 3.7 tests.

**Comment by kbattocchi** [comment]
I'm going to defer the docstring updates to a subsequent PR, because there are some additional changes to our name propagation logic that I think would simplify things and which can all go in together.

**Pull request merged**
