### PR TITLE
Prepare v0.6 release

### PR DESCRIPTION
**Pull request by kbattocchi**

### CODE REVIEW

**Comment by kbattocchi** [comment]
Won't merge until #177 is complete.

**Comment by vasilismsr** [comment]
Can we maybe call it .51 

Doesn’t seem a big delta from .5

**Comment by kbattocchi** [comment]
@vasilismsr Doesn't seem so small to me - aren't the forest learners, and non-parametric DML, and CATE interpreters important additions?  I believe that most packages use [semantic versioning](https://semver.org/), so a release like 0.5.1 would indicate only bugfixes, not new features, although I think most people are pretty forgiving of other schemes pre-1.0.

**Comment by vasilismsr** [comment]
Agreed!

**Pull request merged**
