### PR TITLE
Switch to macOS 10.13 to mitigate CI delays

### PR DESCRIPTION
**Pull request by kbattocchi**
We've been experiencing long delays with our CI builds, somehow involving the jobs that run on macOS; this PR is a temporary measure to see if we can mitigate the issue by using a different OS version.

### CODE REVIEW

**Comment by moprescu** [comment]
Looks good to me!

**Comment by kbattocchi** [comment]
@moprescu Didn't work, though :(

**Comment by kbattocchi** [comment]
Closed PR as the root cause on the Azure DevOps side seems to have been resolved.

**Comment by kbattocchi** [comment]
Reopening to deal with the builds once again being slow.

**Pull request merged**
