### PR TITLE
Remove deprecated functionality

### PR DESCRIPTION
**Pull request by kbattocchi**

### CODE REVIEW

**Comment by fverac** [comment]
NonparametricTwoStageLeastSquares is still referenced a few times (once in Detailed Estimator Comparison and once in DPolynomialFeatures) 
https://github.com/microsoft/EconML/blob/kebatt/removeDeprecated/doc/spec/comparison.rst#id3
[econml\iv\sieve\_tsls.py line 93](https://github.com/microsoft/EconML/blob/kebatt/removeDeprecated/econml/iv/sieve/_tsls.py#L93)

This may also be the case for other deprecated classes, I just noticed this one. 

I would have made a comment on the exact lines themselves but I'm not sure github allows that currently.

**Comment by fverac** [comment]
Also references to old classes `ForestDML` here:
https://github.com/microsoft/EconML/blob/kebatt/removeDeprecated/notebooks/ForestLearners%20Basic%20Example.ipynb

**Comment by fverac** [comment]
Reference to old `ContinuousTreatmentOrthoForest` in https://github.com/microsoft/EconML/blob/kebatt/removeDeprecated/notebooks/Causal%20Forest%20and%20Orthogonal%20Random%20Forest%20Examples.ipynb

**Comment by fverac** [comment]
Reference to old `DiscreteTreatmentOrthoForest` in docs at 
https://github.com/microsoft/EconML/blob/kebatt/removeDeprecated/doc/spec/estimation/dr.rst

**Comment by kbattocchi** [comment]
@fverac I've addressed your issues, please review

**Review by fverac — APPROVED** [review]

**Pull request merged**
